config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :products do
    resources :comments, shallow: true, only: %i[create update edit destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_product, only: %i[show edit update destroy]

  def index
    @products = Product.order(created_at: :desc)
    @products = Product.all
    @product = Product.new

    # 获取选中的选项值
    selected_filling = params[:filling]

    # 将选项值保存到数据库
    Product.create(filling: selected_filling)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to '/products', notice: '品項新增成功'
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: '已更新成功'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: '已成功刪除'
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :inventory_quantity, :description, :image)
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class Users::SessionsController < Devise::SessionsController
    
    def after_sign_out_path_for(_resource_or_scope)
      root_path
    end

    def after_sign_in_path_for(_resource_or_scope)
      root_path
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>黃金萬兩｜草莓大福</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= render 'shared/navbar_top' %>
    </div>
    <main class="container px-5 mt-28">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <div>      
      <%= render 'shared/navbar_bottom' %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<%=  form_for(@product) do |form| %>
    <section class="relative flex justify-center p-5 m-10 hollow_btn">
        <%= link_to root_path do %>
            <div class="absolute right-2 top-2">
                <i class="fa-solid fa-xmark fa-2xl" style="color: #d14d72;"></i>
            </div>
        <% end %> 
        
        <section class="mt-8">
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200 "><%=  form.label :title, "商品品名"%></span>
                <%=  form.text_field :title, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :price, "商品售價"%></span>
                <%=  form.text_field :price, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :description, "商品成分"%></span>
                <%=  form.text_field :description, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :inventory_quantity, "庫存數量"%></span>
                <%=  form.text_field :inventory_quantity, class: "hollow_btn"%>

            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :image, "上傳照片"%></span>
                <%=  form.text_field :image, class: "hollow_btn"%>
            </div>
            <div class="flex justify-center w-full my-4 solid_btn">
                <%=  form.submit "確認更新"%>
            </div>
        </section>
    </section>
<% end %>

app/views/products/index.html.erb
<% if current_user && current_user.role == 0 %>
    <div class="flex justify-end">
    <div class="inline-block m-4 solid_btn">
        <i class="fa-solid fa-plus" style="color: #fff"></i>
        <%= link_to '新增商品', new_product_path %>
    </div>
    </div>
<% end %>
<% @products.each do |product| %>
    <section class="grid grid-cols-1 m-16 ">
        <div class="flex flex-wrap gap-4 p-6 rounded-lg shadow-[0_10px_35px_rgba(0,0,0,0.25)]">
            <div class="flex justify-between w-full gap-2">
                <div class="text-2xl font-bold border-b-8 border-yellow-200 ">
                    <%= product.title %>
                </div>
                <div>
                    <% if current_user && current_user.role == 0 %>
                        <%= link_to edit_product_path(product.id) do %>
                            <i class="fa-regular fa-pen-to-square fa-xl" style="color: #d14d72;"></i>
                        <% end %>
                        <%= link_to product_path(product.id),
                                                            class: "icon icon-danger", 
                                                            method: "delete", 
                                                            data: {confirm: "確認刪除?"} do %>
                            <i class="fa-regular fa-trash-can fa-xl" style="color: #d14d72;"></i>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="w-full"><img src="https://fakeimg.pl/350x200/ff0000,128/000,255" class="w-full h-full object-fit"></div>
            <div class="w-full">成分：<%= product.description %></div>

            <% if product.title == '草莓大福'||  product.title == '原味乳酪'||  product.title == '抹茶乳酪' %>
                <%=  form_for(@product) do |f| %>
                    <%= f.label :filling, "請選擇內餡" %>
                    <%= f.select :filling, options_for_select([['紅豆', '紅豆'], ['芋頭', '芋頭']]) %>
                <% end %>
            <% end %> 
            
            <div class="grid w-full grid-cols-3 gap-4">
                <span class="p-2 text-center text-[#d14d72] hollow_btn hover:solid_btn cursor-pointer">單顆</span>
                <span class="p-2 text-center text-[#d14d72] hollow_btn hover:solid_btn cursor-pointer">6入/盒</span>
                <span class="p-2 text-center text-[#d14d72] hollow_btn hover:solid_btn cursor-pointer">9入/盒</span>
            </div>
            <div class="grid w-full grid-cols-1 gap-4">
                <span class="p-2 text-center text-[#fff] solid_btn hover:bg-[#b83d5c] cursor-pointer">加入購物車</span>
            </div>
        </div>
    </section>
<% end %>

app/views/products/new.html.erb
<%=  form_for(@product) do |form| %>
    <section class="relative flex justify-center p-5 m-10 hollow_btn">
        <%= link_to root_path do %>
            <div class="absolute right-2 top-2">
                    <i class="fa-solid fa-xmark fa-2xl" style="color: #d14d72;"></i>
            </div>
        <% end %> 
        
        <section class="mt-8">
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200 "><%=  form.label :title, "商品品名"%></span>
                <%=  form.text_field :title, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :price, "商品售價"%></span>
                <%=  form.text_field :price, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :description, "商品成分"%></span>
                <%=  form.text_field :description, class: "hollow_btn"%>
            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :inventory_quantity, "庫存數量"%></span>
                <%=  form.text_field :inventory_quantity, class: "hollow_btn"%>

            </div>
            <div class="pb-2 text-[#d14d72]">
                <span class="mr-2 border-b-8 border-yellow-200"><%=  form.label :image, "上傳照片"%></span>
                <%=  form.text_field :image, class: "hollow_btn"%>
            </div>
            <div class="flex justify-center w-full my-4 solid_btn">
                <%=  form.submit "確認新增"%>
            </div>
        </section>
    </section>
<% end %>

app/views/products/show.html.erb
<div class="flex justify-end">
  <div class="inline-block m-4 solid_btn">
    <i class="fa-solid fa-house-chimney" style="color: #fff;"></i>
    <%= link_to '返回首頁', root_path %>
  </div>
</div>

<section class="grid grid-cols-1 p-2 m-4 ">
    <div class="flex flex-wrap gap-4 p-6 rounded-lg shadow-[0_10px_35px_rgba(0,0,0,0.25)]">
        <div class="flex justify-between w-full gap-2">
            <div class="text-2xl font-bold border-b-8 border-yellow-200 ">
                <%= @product.title %>
            </div>
        </div>
        <div><img src="https://fakeimg.pl/350x200/ff0000,128/000,255"></div>
        <div>成分：<%= @product.description %></div>
    </div>
</section>

app/views/shared/_navbar_bottom.html.erb
<div class="fixed bottom-0 w-full">
    <input type="checkbox" name="" id="nav_switch">
    <header class=" main-header">
        <%= link_to root_path do %>
            <i class="fa-solid fa-house-chimney fa-xl" style="color: #d14d72;"></i>
        <% end %>
        <% if current_user.blank? %>
            <%= link_to new_user_session_path do %>
                <i class="fa-solid fa-user fa-xl" style="color: #d14d72;"></i>
            <% end  %>
        <% else %>
            <%= button_to destroy_user_session_path, method: "delete", class: "btn-round btn-sm btn-gray" do %>
                <i class="fa-solid fa-right-from-bracket fa-xl" style="color: #d14d72;"></i>
            <% end %>
        <% end %>
        <%= link_to '#' do %>
            <i class="fa-solid fa-cart-shopping fa-xl" style="color: #d14d72;"></i>
        <% end %>
        <label for="nav_switch" class="cursor-pointer hb">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <nav class="main-nav">
            <ul>
                <li><%= link_to '關於我們' %></li>
                <li><%= link_to '線上購物' %></li>
                <li><%= link_to '訂購須知' %></li>
                <li><%= link_to '查詢訂單' %></li>
                <li>
                    <div class="flex justify-center gap-3">
                        <div><i class="cursor-pointer fa-brands fa-facebook fa-xl" style="color: #d14d72;"></i></div>
                        <div><i class="cursor-pointer fa-brands fa-square-instagram fa-xl" style="color: #d14d72;"></i></div>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
</div>

app/views/shared/_navbar_top.html.erb
<header class="flex justify-center bg-[#fcc8d1] p-2 text-[#d14d72] text-2xl font-bold">
    <h1 id="logo">
        <%= link_to root_path do %>
            <%= image_tag('mochi.png', size: '45x45', class: 'inline-block pr-2') %>
            黃金萬兩｜草莓大福
        <% end %>
    </h1>
</header>